// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newNoteLink(db *gorm.DB, opts ...gen.DOOption) noteLink {
	_noteLink := noteLink{}

	_noteLink.noteLinkDo.UseDB(db, opts...)
	_noteLink.noteLinkDo.UseModel(&model.NoteLink{})

	tableName := _noteLink.noteLinkDo.TableName()
	_noteLink.ALL = field.NewAsterisk(tableName)
	_noteLink.ID = field.NewInt64(tableName, "id")
	_noteLink.SourceNoteID = field.NewInt64(tableName, "source_note_id")
	_noteLink.TargetPath = field.NewString(tableName, "target_path")
	_noteLink.TargetPathHash = field.NewString(tableName, "target_path_hash")
	_noteLink.LinkText = field.NewString(tableName, "link_text")
	_noteLink.IsEmbed = field.NewInt64(tableName, "is_embed")
	_noteLink.VaultID = field.NewInt64(tableName, "vault_id")
	_noteLink.UID = field.NewInt64(tableName, "uid")
	_noteLink.CreatedAt = field.NewField(tableName, "created_at")

	_noteLink.fillFieldMap()

	return _noteLink
}

type noteLink struct {
	noteLinkDo noteLinkDo

	ALL            field.Asterisk
	ID             field.Int64
	SourceNoteID   field.Int64
	TargetPath     field.String
	TargetPathHash field.String
	LinkText       field.String
	IsEmbed        field.Int64
	VaultID        field.Int64
	UID            field.Int64
	CreatedAt      field.Field

	fieldMap map[string]field.Expr
}

func (n noteLink) Table(newTableName string) *noteLink {
	n.noteLinkDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteLink) As(alias string) *noteLink {
	n.noteLinkDo.DO = *(n.noteLinkDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteLink) updateTableName(table string) *noteLink {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.SourceNoteID = field.NewInt64(table, "source_note_id")
	n.TargetPath = field.NewString(table, "target_path")
	n.TargetPathHash = field.NewString(table, "target_path_hash")
	n.LinkText = field.NewString(table, "link_text")
	n.IsEmbed = field.NewInt64(table, "is_embed")
	n.VaultID = field.NewInt64(table, "vault_id")
	n.UID = field.NewInt64(table, "uid")
	n.CreatedAt = field.NewField(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *noteLink) WithContext(ctx context.Context) INoteLinkDo { return n.noteLinkDo.WithContext(ctx) }

func (n noteLink) TableName() string { return n.noteLinkDo.TableName() }

func (n noteLink) Alias() string { return n.noteLinkDo.Alias() }

func (n noteLink) Columns(cols ...field.Expr) gen.Columns { return n.noteLinkDo.Columns(cols...) }

func (n *noteLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteLink) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 9)
	n.fieldMap["id"] = n.ID
	n.fieldMap["source_note_id"] = n.SourceNoteID
	n.fieldMap["target_path"] = n.TargetPath
	n.fieldMap["target_path_hash"] = n.TargetPathHash
	n.fieldMap["link_text"] = n.LinkText
	n.fieldMap["is_embed"] = n.IsEmbed
	n.fieldMap["vault_id"] = n.VaultID
	n.fieldMap["uid"] = n.UID
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n noteLink) clone(db *gorm.DB) noteLink {
	n.noteLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteLink) replaceDB(db *gorm.DB) noteLink {
	n.noteLinkDo.ReplaceDB(db)
	return n
}

type noteLinkDo struct{ gen.DO }

type INoteLinkDo interface {
	gen.SubQuery
	Debug() INoteLinkDo
	WithContext(ctx context.Context) INoteLinkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteLinkDo
	WriteDB() INoteLinkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteLinkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteLinkDo
	Not(conds ...gen.Condition) INoteLinkDo
	Or(conds ...gen.Condition) INoteLinkDo
	Select(conds ...field.Expr) INoteLinkDo
	Where(conds ...gen.Condition) INoteLinkDo
	Order(conds ...field.Expr) INoteLinkDo
	Distinct(cols ...field.Expr) INoteLinkDo
	Omit(cols ...field.Expr) INoteLinkDo
	Join(table schema.Tabler, on ...field.Expr) INoteLinkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteLinkDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteLinkDo
	Group(cols ...field.Expr) INoteLinkDo
	Having(conds ...gen.Condition) INoteLinkDo
	Limit(limit int) INoteLinkDo
	Offset(offset int) INoteLinkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteLinkDo
	Unscoped() INoteLinkDo
	Create(values ...*model.NoteLink) error
	CreateInBatches(values []*model.NoteLink, batchSize int) error
	Save(values ...*model.NoteLink) error
	First() (*model.NoteLink, error)
	Take() (*model.NoteLink, error)
	Last() (*model.NoteLink, error)
	Find() ([]*model.NoteLink, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteLink, err error)
	FindInBatches(result *[]*model.NoteLink, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteLink) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteLinkDo
	Assign(attrs ...field.AssignExpr) INoteLinkDo
	Joins(fields ...field.RelationField) INoteLinkDo
	Preload(fields ...field.RelationField) INoteLinkDo
	FirstOrInit() (*model.NoteLink, error)
	FirstOrCreate() (*model.NoteLink, error)
	FindByPage(offset int, limit int) (result []*model.NoteLink, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteLinkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteLinkDo) Debug() INoteLinkDo {
	return n.withDO(n.DO.Debug())
}

func (n noteLinkDo) WithContext(ctx context.Context) INoteLinkDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteLinkDo) ReadDB() INoteLinkDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteLinkDo) WriteDB() INoteLinkDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteLinkDo) Session(config *gorm.Session) INoteLinkDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteLinkDo) Clauses(conds ...clause.Expression) INoteLinkDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteLinkDo) Returning(value interface{}, columns ...string) INoteLinkDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteLinkDo) Not(conds ...gen.Condition) INoteLinkDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteLinkDo) Or(conds ...gen.Condition) INoteLinkDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteLinkDo) Select(conds ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteLinkDo) Where(conds ...gen.Condition) INoteLinkDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteLinkDo) Order(conds ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteLinkDo) Distinct(cols ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteLinkDo) Omit(cols ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteLinkDo) Join(table schema.Tabler, on ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteLinkDo) Group(cols ...field.Expr) INoteLinkDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteLinkDo) Having(conds ...gen.Condition) INoteLinkDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteLinkDo) Limit(limit int) INoteLinkDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteLinkDo) Offset(offset int) INoteLinkDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteLinkDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteLinkDo) Unscoped() INoteLinkDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteLinkDo) Create(values ...*model.NoteLink) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteLinkDo) CreateInBatches(values []*model.NoteLink, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteLinkDo) Save(values ...*model.NoteLink) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteLinkDo) First() (*model.NoteLink, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteLink), nil
	}
}

func (n noteLinkDo) Take() (*model.NoteLink, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteLink), nil
	}
}

func (n noteLinkDo) Last() (*model.NoteLink, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteLink), nil
	}
}

func (n noteLinkDo) Find() ([]*model.NoteLink, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteLink), err
}

func (n noteLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteLink, err error) {
	buf := make([]*model.NoteLink, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteLinkDo) FindInBatches(result *[]*model.NoteLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteLinkDo) Attrs(attrs ...field.AssignExpr) INoteLinkDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteLinkDo) Assign(attrs ...field.AssignExpr) INoteLinkDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteLinkDo) Joins(fields ...field.RelationField) INoteLinkDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteLinkDo) Preload(fields ...field.RelationField) INoteLinkDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteLinkDo) FirstOrInit() (*model.NoteLink, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteLink), nil
	}
}

func (n noteLinkDo) FirstOrCreate() (*model.NoteLink, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteLink), nil
	}
}

func (n noteLinkDo) FindByPage(offset int, limit int) (result []*model.NoteLink, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteLinkDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteLinkDo) Delete(models ...*model.NoteLink) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteLinkDo) withDO(do gen.Dao) *noteLinkDo {
	n.DO = *do.(*gen.DO)
	return n
}
