// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/haierkeys/fast-note-sync-service/internal/model"
)

func newGitSyncHistory(db *gorm.DB, opts ...gen.DOOption) gitSyncHistory {
	_gitSyncHistory := gitSyncHistory{}

	_gitSyncHistory.gitSyncHistoryDo.UseDB(db, opts...)
	_gitSyncHistory.gitSyncHistoryDo.UseModel(&model.GitSyncHistory{})

	tableName := _gitSyncHistory.gitSyncHistoryDo.TableName()
	_gitSyncHistory.ALL = field.NewAsterisk(tableName)
	_gitSyncHistory.ID = field.NewInt64(tableName, "id")
	_gitSyncHistory.UID = field.NewInt64(tableName, "uid")
	_gitSyncHistory.ConfigID = field.NewInt64(tableName, "config_id")
	_gitSyncHistory.StartTime = field.NewTime(tableName, "start_time")
	_gitSyncHistory.EndTime = field.NewTime(tableName, "end_time")
	_gitSyncHistory.Status = field.NewInt64(tableName, "status")
	_gitSyncHistory.Message = field.NewString(tableName, "message")
	_gitSyncHistory.CreatedAt = field.NewField(tableName, "created_at")
	_gitSyncHistory.UpdatedAt = field.NewField(tableName, "updated_at")

	_gitSyncHistory.fillFieldMap()

	return _gitSyncHistory
}

type gitSyncHistory struct {
	gitSyncHistoryDo gitSyncHistoryDo

	ALL       field.Asterisk
	ID        field.Int64
	UID       field.Int64
	ConfigID  field.Int64
	StartTime field.Time
	EndTime   field.Time
	Status    field.Int64
	Message   field.String
	CreatedAt field.Field
	UpdatedAt field.Field

	fieldMap map[string]field.Expr
}

func (g gitSyncHistory) Table(newTableName string) *gitSyncHistory {
	g.gitSyncHistoryDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gitSyncHistory) As(alias string) *gitSyncHistory {
	g.gitSyncHistoryDo.DO = *(g.gitSyncHistoryDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gitSyncHistory) updateTableName(table string) *gitSyncHistory {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.UID = field.NewInt64(table, "uid")
	g.ConfigID = field.NewInt64(table, "config_id")
	g.StartTime = field.NewTime(table, "start_time")
	g.EndTime = field.NewTime(table, "end_time")
	g.Status = field.NewInt64(table, "status")
	g.Message = field.NewString(table, "message")
	g.CreatedAt = field.NewField(table, "created_at")
	g.UpdatedAt = field.NewField(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *gitSyncHistory) WithContext(ctx context.Context) IGitSyncHistoryDo {
	return g.gitSyncHistoryDo.WithContext(ctx)
}

func (g gitSyncHistory) TableName() string { return g.gitSyncHistoryDo.TableName() }

func (g gitSyncHistory) Alias() string { return g.gitSyncHistoryDo.Alias() }

func (g gitSyncHistory) Columns(cols ...field.Expr) gen.Columns {
	return g.gitSyncHistoryDo.Columns(cols...)
}

func (g *gitSyncHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gitSyncHistory) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 9)
	g.fieldMap["id"] = g.ID
	g.fieldMap["uid"] = g.UID
	g.fieldMap["config_id"] = g.ConfigID
	g.fieldMap["start_time"] = g.StartTime
	g.fieldMap["end_time"] = g.EndTime
	g.fieldMap["status"] = g.Status
	g.fieldMap["message"] = g.Message
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g gitSyncHistory) clone(db *gorm.DB) gitSyncHistory {
	g.gitSyncHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gitSyncHistory) replaceDB(db *gorm.DB) gitSyncHistory {
	g.gitSyncHistoryDo.ReplaceDB(db)
	return g
}

type gitSyncHistoryDo struct{ gen.DO }

type IGitSyncHistoryDo interface {
	gen.SubQuery
	Debug() IGitSyncHistoryDo
	WithContext(ctx context.Context) IGitSyncHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGitSyncHistoryDo
	WriteDB() IGitSyncHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGitSyncHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGitSyncHistoryDo
	Not(conds ...gen.Condition) IGitSyncHistoryDo
	Or(conds ...gen.Condition) IGitSyncHistoryDo
	Select(conds ...field.Expr) IGitSyncHistoryDo
	Where(conds ...gen.Condition) IGitSyncHistoryDo
	Order(conds ...field.Expr) IGitSyncHistoryDo
	Distinct(cols ...field.Expr) IGitSyncHistoryDo
	Omit(cols ...field.Expr) IGitSyncHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo
	Group(cols ...field.Expr) IGitSyncHistoryDo
	Having(conds ...gen.Condition) IGitSyncHistoryDo
	Limit(limit int) IGitSyncHistoryDo
	Offset(offset int) IGitSyncHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGitSyncHistoryDo
	Unscoped() IGitSyncHistoryDo
	Create(values ...*model.GitSyncHistory) error
	CreateInBatches(values []*model.GitSyncHistory, batchSize int) error
	Save(values ...*model.GitSyncHistory) error
	First() (*model.GitSyncHistory, error)
	Take() (*model.GitSyncHistory, error)
	Last() (*model.GitSyncHistory, error)
	Find() ([]*model.GitSyncHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GitSyncHistory, err error)
	FindInBatches(result *[]*model.GitSyncHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GitSyncHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGitSyncHistoryDo
	Assign(attrs ...field.AssignExpr) IGitSyncHistoryDo
	Joins(fields ...field.RelationField) IGitSyncHistoryDo
	Preload(fields ...field.RelationField) IGitSyncHistoryDo
	FirstOrInit() (*model.GitSyncHistory, error)
	FirstOrCreate() (*model.GitSyncHistory, error)
	FindByPage(offset int, limit int) (result []*model.GitSyncHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGitSyncHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gitSyncHistoryDo) Debug() IGitSyncHistoryDo {
	return g.withDO(g.DO.Debug())
}

func (g gitSyncHistoryDo) WithContext(ctx context.Context) IGitSyncHistoryDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gitSyncHistoryDo) ReadDB() IGitSyncHistoryDo {
	return g.Clauses(dbresolver.Read)
}

func (g gitSyncHistoryDo) WriteDB() IGitSyncHistoryDo {
	return g.Clauses(dbresolver.Write)
}

func (g gitSyncHistoryDo) Session(config *gorm.Session) IGitSyncHistoryDo {
	return g.withDO(g.DO.Session(config))
}

func (g gitSyncHistoryDo) Clauses(conds ...clause.Expression) IGitSyncHistoryDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gitSyncHistoryDo) Returning(value interface{}, columns ...string) IGitSyncHistoryDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gitSyncHistoryDo) Not(conds ...gen.Condition) IGitSyncHistoryDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gitSyncHistoryDo) Or(conds ...gen.Condition) IGitSyncHistoryDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gitSyncHistoryDo) Select(conds ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gitSyncHistoryDo) Where(conds ...gen.Condition) IGitSyncHistoryDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gitSyncHistoryDo) Order(conds ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gitSyncHistoryDo) Distinct(cols ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gitSyncHistoryDo) Omit(cols ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gitSyncHistoryDo) Join(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gitSyncHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gitSyncHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gitSyncHistoryDo) Group(cols ...field.Expr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gitSyncHistoryDo) Having(conds ...gen.Condition) IGitSyncHistoryDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gitSyncHistoryDo) Limit(limit int) IGitSyncHistoryDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gitSyncHistoryDo) Offset(offset int) IGitSyncHistoryDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gitSyncHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGitSyncHistoryDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gitSyncHistoryDo) Unscoped() IGitSyncHistoryDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gitSyncHistoryDo) Create(values ...*model.GitSyncHistory) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gitSyncHistoryDo) CreateInBatches(values []*model.GitSyncHistory, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gitSyncHistoryDo) Save(values ...*model.GitSyncHistory) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gitSyncHistoryDo) First() (*model.GitSyncHistory, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncHistory), nil
	}
}

func (g gitSyncHistoryDo) Take() (*model.GitSyncHistory, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncHistory), nil
	}
}

func (g gitSyncHistoryDo) Last() (*model.GitSyncHistory, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncHistory), nil
	}
}

func (g gitSyncHistoryDo) Find() ([]*model.GitSyncHistory, error) {
	result, err := g.DO.Find()
	return result.([]*model.GitSyncHistory), err
}

func (g gitSyncHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GitSyncHistory, err error) {
	buf := make([]*model.GitSyncHistory, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gitSyncHistoryDo) FindInBatches(result *[]*model.GitSyncHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gitSyncHistoryDo) Attrs(attrs ...field.AssignExpr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gitSyncHistoryDo) Assign(attrs ...field.AssignExpr) IGitSyncHistoryDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gitSyncHistoryDo) Joins(fields ...field.RelationField) IGitSyncHistoryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gitSyncHistoryDo) Preload(fields ...field.RelationField) IGitSyncHistoryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gitSyncHistoryDo) FirstOrInit() (*model.GitSyncHistory, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncHistory), nil
	}
}

func (g gitSyncHistoryDo) FirstOrCreate() (*model.GitSyncHistory, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GitSyncHistory), nil
	}
}

func (g gitSyncHistoryDo) FindByPage(offset int, limit int) (result []*model.GitSyncHistory, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gitSyncHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gitSyncHistoryDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gitSyncHistoryDo) Delete(models ...*model.GitSyncHistory) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gitSyncHistoryDo) withDO(do gen.Dao) *gitSyncHistoryDo {
	g.DO = *do.(*gen.DO)
	return g
}
